import { AdminHeader } from "@/components"
import { AdminContainer } from "@/components/routing/AdminContainer"
import { Sidebar } from "@/components/routing/Sidebar"
import { MainThemeProvider } from "@/providers"
import { Inter, Laila, Montserrat } from "next/font/google"
import "../globals.css"

const inter = Inter({
    subsets: ["latin", "cyrillic", "latin-ext", "cyrillic-ext"],
    variable: "--font-inter",
})
const montserrat = Montserrat({
    subsets: ["latin", "cyrillic", "latin-ext", "cyrillic-ext"],
    variable: "--font-montserrat",
})
const laila = Laila({
    subsets: ["latin", "latin-ext"],
    weight: "500",
    variable: "--font-laila",
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <MainThemeProvider>
                <Sidebar />
                <div className=" flex flex-col ml-[251px] h-screen bg-[#F1F1F4] dark:bg-black">
                    <AdminHeader />
                    <AdminContainer>{children}</AdminContainer>
                </div>
            </MainThemeProvider>
        </>
    )
}
