import { AdminHeader } from "@/components";
import { AdminContainer } from "@/components/routing/AdminContainer";
import { Sidebar } from "@/components/routing/Sidebar";
import { MainThemeProvider } from "@/providers";
import { Inter, Laila, Montserrat } from 'next/font/google';
import '../globals.css';

const inter = Inter({ subsets: ['latin', 'cyrillic', 'latin-ext', 'cyrillic-ext'], variable: "--font-inter" });
const montserrat = Montserrat({ subsets: ['latin', 'cyrillic', 'latin-ext', 'cyrillic-ext'], variable: "--font-montserrat" });
const laila = Laila({ subsets: ['latin', 'latin-ext'], weight: "500", variable: "--font-laila" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html className="h-full" suppressHydrationWarning lang="en">
        <body className={`h-full ${inter.variable} ${montserrat.variable} ${laila.variable} font-montserrat bg-[#F1F1F4] dark:bg-black`}>
          <MainThemeProvider>
            <Sidebar />
            <div className="flex flex-col ml-[251px] h-full">
              <AdminHeader />
              <AdminContainer>
                {children}
              </AdminContainer>
            </div>
          </MainThemeProvider>
        </body>
      </html>
    </>
  )
}